Enhancement to allow the use of namespaces for the output topic
simchanu29/ros_simple_teleop pull request #4
Opened 2018-06-19 12:35 UTC by fcebron

I tried to use your code in my project but I had issues with this line of code to have a NameSpace for the output topic... So I suggest these changes.

2018-06-19 15:15 UTC, simchanu29 requested changes
En français c'est plus simple ;)
En effet ça peut être restrictif, malgré tout j'aurai plutôt opté pour un paramètre `prefix` (et non pas `~prefix`) du lancement du noeud initialisé vide. Je préfère pouvoir mettre un prefix devant le type de donnée que j'envoie.

Du coup je valide pas, soit tu fais la modif, soit je la fait dans les prochains jours.

ça donnerai donc : 
`prefix = rospy.get_param('prefix','')`
`cmd_pub = rospy.Publisher(prefix+topic_name, Msg_class, queue_size=1)`

2018-06-19 15:35 UTC, fcebron commented
Je vais te faire ça.

Au passage je ne comprends pas tes lignes de déclaration dans le launchfile : 
`<arg name="config_path"/>`
`<rosparam file="$(arg config_path)"/>`

Je pense avoir diagnostiqué que ces deux lignes invalident la vérification du package (`rosrun roslaunch roslaunch-check ros_teleop/launch/`)

2018-06-19 15:38 UTC, simchanu29 commented
Ce sont des lignes pour déclarer les arguments d'un launchfile.
Quand tu fais un launchfile il est possible de lui déclarer des arguments qui faut alors préciser quand on fait un include.

Je vais vérifier si il y a pas une coquille à cet endroit là mais ça me parait ok.

2018-06-19 15:39 UTC, simchanu29 commented
Je confirrme c'est ok. Il est fait pour pouvoir être appelé depuis un autre package. Un exemple pour tester le package se situe dans test.launch

2018-06-19 15:44 UTC, fcebron commented
Ok, donc c'est le code de vérification des launchfiles qui ne prends pas ça en compte.

Que penses-tu de ça ?
`prefix = rospy.get_param('prefix','')`
`localPrefix = rospy.get_param('~prefix', '')`
`cmd_pub = rospy.Publisher(prefix + localPrefix + topic_name, Msg_class, queue_size=1)`

Je ne trouve pas l'équivalent propre de 
`if (n.getParam("prefix", prefix)) { // Getting param content...`
en python...

2018-06-19 18:00 UTC, simchanu29 commented
ça me parait bien. Pourquoi local_prefix ?

2018-06-19 18:33 UTC, fcebron commented
Pour le cas où les gens ont besoin d'une variable privée (si j'ai bien compris le ~). Par défaut j'aurais pas nommé "prefix" mais "ros_teleop_prefix" (j'ai eu un bug lié à l'écrasement d'une variable récemment, depuis je nomme tout de manière unique).

2018-06-20 12:25 UTC, fcebron commented
C'est corrigé, tu peux débloquer le pull-request !

2018-06-20 16:43 UTC, simchanu29 approved these changes

2018-06-20 16:43 UTC, merged